
compute-api/src/v2.1/wadl/diagnostics-v2.1.wadl:
    title: OpenStack Compute API v2.1
    output_directory: dist/diagnostics
compute-api/src/v2.1/wadl/extensions-v2.1.wadl:
    title: OpenStack Compute API v2.1
    output_directory: dist/extensions
compute-api/src/v2.1/wadl/flavors-v2.1.wadl:
    title: OpenStack Compute API v2.1
    output_directory: dist/flavors
compute-api/src/v2.1/wadl/images-v2.1.wadl:
    title: OpenStack Compute API v2.1
    output_directory: dist/images
compute-api/src/v2.1/wadl/ips-v2.1.wadl:
    title: OpenStack Compute API v2.1
    output_directory: dist/ips
compute-api/src/v2.1/wadl/limits-v2.1.wadl:
    title: OpenStack Compute API v2.1
    output_directory: dist/limits
compute-api/src/v2.1/wadl/metadata-v2.1.wadl:
    title: OpenStack Compute API v2.1
    output_directory: dist/metadata
compute-api/src/v2.1/wadl/os-agents-v2.1.wadl:
    title: OpenStack Compute API v2.1
    output_directory: dist/os-agents
compute-api/src/v2.1/wadl/os-aggregates-v2.1.wadl:
    title: OpenStack Compute API v2.1
    output_directory: dist/os-aggregates
compute-api/src/v2.1/wadl/os-assisted-volume-snapshots-v2.1.wadl:
    title: OpenStack Compute API v2.1
    output_directory: dist/os-assisted-volume-snapshots
compute-api/src/v2.1/wadl/os-availability-zone-v2.1.wadl:
    title: OpenStack Compute API v2.1
    output_directory: dist/os-availability-zone
compute-api/src/v2.1/wadl/os-baremetal-nodes-v2.1.wadl:
    title: OpenStack Compute API v2.1
    output_directory: dist/os-baremetal-nodes
compute-api/src/v2.1/wadl/os-cells-v2.1.wadl:
    title: OpenStack Compute API v2.1
    output_directory: dist/os-cells
compute-api/src/v2.1/wadl/os-certificates-v2.1.wadl:
    title: OpenStack Compute API v2.1
    output_directory: dist/os-certificates
compute-api/src/v2.1/wadl/os-cloudpipe-v2.1.wadl:
    title: OpenStack Compute API v2.1
    output_directory: dist/os-cloudpipe
compute-api/src/v2.1/wadl/os-consoles-v2.1.wadl:
    title: OpenStack Compute API v2.1
    output_directory: dist/os-consoles
compute-api/src/v2.1/wadl/os-disk-config-v2.1.wadl:
    title: OpenStack Compute API v2.1
    output_directory: dist/os-disk-config
compute-api/src/v2.1/wadl/os-fixed-ips-v2.1.wadl:
    title: OpenStack Compute API v2.1
    output_directory: dist/os-fixed-ips
compute-api/src/v2.1/wadl/os-flavor-access-v2.1.wadl:
    title: OpenStack Compute API v2.1
    output_directory: dist/os-flavor-access
compute-api/src/v2.1/wadl/os-flavor-extra-specs-v2.1.wadl:
    title: OpenStack Compute API v2.1
    output_directory: dist/os-flavor-extra-specs
compute-api/src/v2.1/wadl/os-floating-ip-dns-v2.1.wadl:
    title: OpenStack Compute API v2.1
    output_directory: dist/os-floating-ip-dns
compute-api/src/v2.1/wadl/os-floating-ip-pools-v2.1.wadl:
    title: OpenStack Compute API v2.1
    output_directory: dist/os-floating-ip-pools
compute-api/src/v2.1/wadl/os-floating-ips-bulk-v2.1.wadl:
    title: OpenStack Compute API v2.1
    output_directory: dist/os-floating-ips-bulk
compute-api/src/v2.1/wadl/os-floating-ips-v2.1.wadl:
    title: OpenStack Compute API v2.1
    output_directory: dist/os-floating-ips
compute-api/src/v2.1/wadl/os-fping-v2.1.wadl:
    title: OpenStack Compute API v2.1
    output_directory: dist/os-fping
compute-api/src/v2.1/wadl/os-hosts-v2.1.wadl:
    title: OpenStack Compute API v2.1
    output_directory: dist/os-hosts
compute-api/src/v2.1/wadl/os-hypervisors-v2.1.wadl:
    title: OpenStack Compute API v2.1
    output_directory: dist/os-hypervisors
compute-api/src/v2.1/wadl/os-instance-actions-v2.1.wadl:
    title: OpenStack Compute API v2.1
    output_directory: dist/os-instance-actions
compute-api/src/v2.1/wadl/os-instance-usage-audit-log-v2.1.wadl:
    title: OpenStack Compute API v2.1
    output_directory: dist/os-instance-usage-audit-log
compute-api/src/v2.1/wadl/os-interface-v2.1.wadl:
    title: OpenStack Compute API v2.1
    output_directory: dist/os-interface
compute-api/src/v2.1/wadl/os-keypairs-v2.1.wadl:
    title: OpenStack Compute API v2.1
    output_directory: dist/os-keypairs
compute-api/src/v2.1/wadl/os-migrations-v2.1.wadl:
    title: OpenStack Compute API v2.1
    output_directory: dist/os-migrations
compute-api/src/v2.1/wadl/os-networks-v2.1.wadl:
    title: OpenStack Compute API v2.1
    output_directory: dist/os-networks
compute-api/src/v2.1/wadl/os-quota-class-sets-v2.1.wadl:
    title: OpenStack Compute API v2.1
    output_directory: dist/os-quota-class-sets
compute-api/src/v2.1/wadl/os-quota-sets-v2.1.wadl:
    title: OpenStack Compute API v2.1
    output_directory: dist/os-quota-sets
compute-api/src/v2.1/wadl/os-security-group-default-rules-v2.1.wadl:
    title: OpenStack Compute API v2.1
    output_directory: dist/os-security-group-default-rules
compute-api/src/v2.1/wadl/os-security-group-rules-v2.1.wadl:
    title: OpenStack Compute API v2.1
    output_directory: dist/os-security-group-rules
compute-api/src/v2.1/wadl/os-security-groups-v2.1.wadl:
    title: OpenStack Compute API v2.1
    output_directory: dist/os-security-groups
compute-api/src/v2.1/wadl/os-server-external-events-v2.1.wadl:
    title: OpenStack Compute API v2.1
    output_directory: dist/os-server-external-events
compute-api/src/v2.1/wadl/os-server-groups-v2.1.wadl:
    title: OpenStack Compute API v2.1
    output_directory: dist/os-server-groups
compute-api/src/v2.1/wadl/os-server-password-v2.1.wadl:
    title: OpenStack Compute API v2.1
    output_directory: dist/os-server-password
compute-api/src/v2.1/wadl/os-services-v2.1.wadl:
    title: OpenStack Compute API v2.1
    output_directory: dist/os-services
compute-api/src/v2.1/wadl/os-simple-tenant-usage-v2.1.wadl:
    title: OpenStack Compute API v2.1
    output_directory: dist/os-simple-tenant-usage
compute-api/src/v2.1/wadl/os-tenant-networks-v2.1.wadl:
    title: OpenStack Compute API v2.1
    output_directory: dist/os-tenant-networks
compute-api/src/v2.1/wadl/os-virtual-interfaces-v2.1.wadl:
    title: OpenStack Compute API v2.1
    output_directory: dist/os-virtual-interfaces
compute-api/src/v2.1/wadl/os-volume-attachments-v2.1.wadl:
    title: OpenStack Compute API v2.1
    output_directory: dist/os-volume-attachments
compute-api/src/v2.1/wadl/os-volumes-v2.1.wadl:
    title: OpenStack Compute API v2.1
    output_directory: dist/os-volumes
compute-api/src/v2.1/wadl/servers-action-admin-v2.1.wadl:
    title: OpenStack Compute API v2.1
    output_directory: dist/servers-action-admin
compute-api/src/v2.1/wadl/servers-action-console-output-v2.1.wadl:
    title: OpenStack Compute API v2.1
    output_directory: dist/servers-action-console-output
compute-api/src/v2.1/wadl/servers-action-deferred-delete-v2.1.wadl:
    title: OpenStack Compute API v2.1
    output_directory: dist/servers-action-deferred-delete
compute-api/src/v2.1/wadl/servers-action-evacuate-v2.1.wadl:
    title: OpenStack Compute API v2.1
    output_directory: dist/servers-action-evacuate
compute-api/src/v2.1/wadl/servers-action-fixed-ip-v2.1.wadl:
    title: OpenStack Compute API v2.1
    output_directory: dist/servers-action-fixed-ip
compute-api/src/v2.1/wadl/servers-action-multinic-v2.1.wadl:
    title: OpenStack Compute API v2.1
    output_directory: dist/servers-action-multinic
compute-api/src/v2.1/wadl/servers-action-remote-consoles-v2.1.wadl:
    title: OpenStack Compute API v2.1
    output_directory: dist/servers-action-remote-consoles
compute-api/src/v2.1/wadl/servers-action-shelve-v2.1.wadl:
    title: OpenStack Compute API v2.1
    output_directory: dist/servers-action-shelve
compute-api/src/v2.1/wadl/servers-multiple-create-v2.1.wadl:
    title: OpenStack Compute API v2.1
    output_directory: dist/servers-multiple-create
compute-api/src/v2.1/wadl/servers-v2.1.wadl:
    title: OpenStack Compute API v2.1
    output_directory: dist/servers
compute-api/src/v2.1/wadl/versions-v2.1.wadl:
    title: OpenStack Compute API v2.1
    output_directory: dist/versions
