#
# Compute wadl2rst config file:
#

samples/compute-api/61206-os-migrations-v2.1.wadl:
    title: OpenStack Compute API v2.1
    output_directory: dist

samples/compute-api/6127-security-groups.wadl:
    title: OpenStack Compute API v2.1
    output_directory: dist

samples/compute-api/61864-metadefs-namespaces-v2.wadl:
    title: OpenStack Compute API v2.1
    output_directory: dist

samples/compute-api/62798-os-instance-actions-v2.1.wadl:
    title: OpenStack Compute API v2.1
    output_directory: dist

samples/compute-api/64288-clustering-api.wadl:
    title: OpenStack Compute API v2.1
    output_directory: dist

samples/compute-api/65035-os-vol-image-meta-v2.wadl:
    title: OpenStack Compute API v2.1
    output_directory: dist

samples/compute-api/65155-servers-action-console-output-v2.1.wadl:
    title: OpenStack Compute API v2.1
    output_directory: dist

samples/compute-api/6543-os-floating-ip-pools-v2.1.wadl:
    title: OpenStack Compute API v2.1
    output_directory: dist

samples/compute-api/6622-ports.wadl:
    title: OpenStack Compute API v2.1
    output_directory: dist

samples/compute-api/6949-job-binaries.wadl:
    title: OpenStack Compute API v2.1
    output_directory: dist

samples/compute-api/7591-service-providers.wadl:
    title: OpenStack Compute API v2.1
    output_directory: dist

samples/compute-api/7700-os-assisted-volume-snapshots-v2.1.wadl:
    title: OpenStack Compute API v2.1
    output_directory: dist

samples/compute-api/8000-os-keypairs-v2.1.wadl:
    title: OpenStack Compute API v2.1
    output_directory: dist

samples/compute-api/865-os-fixed-ips-v2.1.wadl:
    title: OpenStack Compute API v2.1
    output_directory: dist

samples/compute-api/8838-metadefs-namespaces-tags-v2.wadl:
    title: OpenStack Compute API v2.1
    output_directory: dist

samples/compute-api/927-OS-KSCATALOG-admin.wadl:
    title: OpenStack Compute API v2.1
    output_directory: dist

samples/compute-api/9448-OS-TRUST-v3.wadl:
    title: OpenStack Compute API v2.1
    output_directory: dist

samples/compute-api/9454-os-quota-sets-v2.1.wadl:
    title: OpenStack Compute API v2.1
    output_directory: dist

samples/compute-api/9565-OS-KSEC2-admin.wadl:
    title: OpenStack Compute API v2.1
    output_directory: dist
